### ISSUE TITLE
it does not create contact

### ISSUE THREAD

**Issue by oremic** [ecoen66/homebridge-dummy-contact#2]
Hi
it does not create contact.
          {
          "accessory": "DummySwitch",
          "name": "switch ad contact",
          "stateful": true,
          "contact": true
        }
![IMG_2FEFB7AD7F2C-1](https://user-images.githubusercontent.com/42227735/103142417-f58b8400-4702-11eb-8038-01f7bc37a4cf.jpeg)

**Comment by ecoen66** [comment]
What version of the plugin are you using?  The config.json doesn't match your screenshot.  My plugin should show a lightbulb unless you have a config entry "switch": true.

**Comment by ecoen66** [comment]
Closing due to lack of interest
