### ISSUE TITLE
incorrect plugin identifier

### ISSUE THREAD

**Issue by ihadx** [ecoen66/homebridge-dummy-contact#5]
I see the following in the log file. Can I safely ignore this?
(I had installed homebridge-dummy previously but discovered I needed the contact sensor so uninstalled that and installed this one)
Plugin 'homebridge-dummy-contact' tried to register with an incorrect plugin identifier: 'homebridge-dummy'. Please report this to the developer!

Thanks

**Comment by ecoen66** [comment]
I'm assuming that this is no longer an issue...  Is it?

**Comment by ihadx** [comment]
I still see the issue in the log. I've upgraded homebridge to 1.3.5 but not yet the plugin.
When I click on the button to upgrade the plugin I see:
The homebridge-dummy-contact plugin recommends running on Node.js v14.17.6 or later. You are currently running Node.js v14.16.0.
I haven't researched this yet. Is upgrading node.js and then the plugin likely to get rid of the error/warning message?

**Comment by ecoen66** [comment]
Corrected in 0.3.7
