### ISSUE TITLE
Contact Sensor missing in Alexa Routines 

### ISSUE THREAD

**Issue by amrishraje** [ecoen66/homebridge-dummy-contact#6]
I was able to create a dummy switch and a corresponding contact sensor. I changed the dummy switch type to switch instead of light build for easier use. I’m able to see both the switch and contact sensor in Alexa app in devices section. Both are enabled. However, I can’t see the contact Sensor as a trigger within routines - smart home devices. I see my other physical contact sensors like Ring contact sensor and can run routines off them. 

However they dummy contract Sensor is missing in routines which defeats the purpose of this plugin all together. Any suggestions? Im happy to post any logs or screen shots needed to debug

**Comment by NorthernMan54** [comment]
Did you enable routines in the homebridge-alexa plugin ?

**Comment by andy2002a** [comment]
> Did you enable routines in the homebridge-alexa plugin ?

That fixed it.
